[workspace]
resolver = "2"
members = ["lib/*", "bin/*"]
package.authors = ["KiraCoding"]
package.rust-version = "1.64.0"
package.edition = "2021"

[profile.release]
codegen-units = 1
strip = true
lto = true
