[workspace]
resolver = "2"
members = ["chip", "chip_assembler", "chip_interpreter", "chip_macro"]
package.authors = ["KiraCoding"]
package.rust-version = "1.64.0"
package.edition = "2021"
package.license = "GPL-3.0-only"

[profile.release]
codegen-units = 1
strip = true
lto = true
