[package]
name = "chip_lexer"
version = "0.1.0"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
itertools = { version = "0.11.0" }
